# Generated by Django 3.2.15 on 2022-09-23 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provedore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProvedor', models.CharField(help_text='Ingrese el Nombre del Provedor', max_length=100)),
                ('apellidoProvedor', models.CharField(help_text='Ingrese el Apellido del Provedor', max_length=100)),
                ('direccionProvedor', models.CharField(help_text='Ingrese la Direccion del Provedor', max_length=100)),
                ('provinciaProvedor', models.CharField(help_text='Ingrese la Provincia del Provedor', max_length=100)),
                ('telefonoProvedor', models.CharField(help_text='Ingrese el Telefono del Provedor', max_length=12)),
            ],
            options={
                'verbose_name': 'provedore',
                'verbose_name_plural': 'provedores',
            },
        ),
        migrations.CreateModel(
            name='Distribuir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProductos', models.CharField(max_length=50, verbose_name='Cantidad Productos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('provedore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provedores.provedore', verbose_name='Provedore')),
            ],
            options={
                'verbose_name': 'distribuir',
            },
        ),
    ]
