# Generated by Django 3.2.15 on 2022-09-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(help_text='Ingrese el Nombre del Cliente', max_length=100)),
                ('apellidosCliente', models.CharField(help_text='Ingrese el Apellido del Cliente', max_length=100)),
                ('direccionCliente', models.CharField(help_text='Ingrese la Direccion del Cliente', max_length=100)),
                ('telefonoCliente', models.CharField(help_text='Ingrese el Telefono del Cliente', max_length=12)),
            ],
        ),
    ]
